// automatically generated by the FlatBuffers compiler, do not modify

import { Monster, MonsterT } from '../../my-game/example/monster';


export enum AnyAmbiguousAliases{
  NONE = 0,
  M1 = 1,
  M2 = 2,
  M3 = 3
}

export function unionToAnyAmbiguousAliases(
  type: AnyAmbiguousAliases,
  accessor: (Type: { new (): Monster }) => Monster|null
): Monster|null {
  switch(type) {
    case AnyAmbiguousAliases.NONE: return null; 
    case AnyAmbiguousAliases.M1: return accessor(Monster);
    case AnyAmbiguousAliases.M2: return accessor(Monster);
    case AnyAmbiguousAliases.M3: return accessor(Monster);
    default: return null;
  }
}

export function unionListToAnyAmbiguousAliases(
  type: AnyAmbiguousAliases, 
  accessor: (index: number, Type: { new (): Monster }) => Monster|null, 
  index: number
): Monster|null {
  switch(type) {
    case AnyAmbiguousAliases.NONE: return null; 
    case AnyAmbiguousAliases.M1: return accessor(index, Monster);
    case AnyAmbiguousAliases.M2: return accessor(index, Monster);
    case AnyAmbiguousAliases.M3: return accessor(index, Monster);
    default: return null;
  }
}

