// automatically generated by the FlatBuffers compiler, do not modify

import { FallingTub, FallingTubT } from './falling-tub';
import { HandFan, HandFanT } from './hand-fan';


export enum Gadget{
  NONE = 0,
  FallingTub = 1,
  HandFan = 2
}

export function unionToGadget(
  type: Gadget,
  accessor: (Type: { new (): FallingTub|HandFan }) => FallingTub|HandFan|null
): FallingTub|HandFan|null {
  switch(type) {
    case Gadget.NONE: return null; 
    case Gadget.FallingTub: return accessor(FallingTub);
    case Gadget.HandFan: return accessor(HandFan);
    default: return null;
  }
}

export function unionListToGadget(
  type: Gadget, 
  accessor: (index: number, Type: { new (): FallingTub|HandFan }) => FallingTub|HandFan|null, 
  index: number
): FallingTub|HandFan|null {
  switch(type) {
    case Gadget.NONE: return null; 
    case Gadget.FallingTub: return accessor(index, FallingTub);
    case Gadget.HandFan: return accessor(index, HandFan);
    default: return null;
  }
}

